# Generated by Django 4.2.5 on 2023-10-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AthleticsFieldClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll", models.IntegerField()),
                ("name", models.CharField(max_length=122)),
                ("joining_year", models.IntegerField()),
                ("designation", models.CharField(max_length=122)),
                ("branch", models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name="AthleticsTrackClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll", models.IntegerField()),
                ("name", models.CharField(max_length=122)),
                ("joining_year", models.IntegerField()),
                ("designation", models.CharField(max_length=122)),
                ("branch", models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name="BadmintonClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll", models.IntegerField()),
                ("name", models.CharField(max_length=122)),
                ("joining_year", models.IntegerField()),
                ("designation", models.CharField(max_length=122)),
                ("branch", models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name="BasketBallClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll", models.IntegerField()),
                ("name", models.CharField(max_length=122)),
                ("joining_year", models.IntegerField()),
                ("designation", models.CharField(max_length=122)),
                ("branch", models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name="CarromClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll", models.IntegerField()),
                ("name", models.CharField(max_length=122)),
                ("joining_year", models.IntegerField()),
                ("designation", models.CharField(max_length=122)),
                ("branch", models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name="ChessClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll", models.IntegerField()),
                ("name", models.CharField(max_length=122)),
                ("joining_year", models.IntegerField()),
                ("designation", models.CharField(max_length=122)),
                ("branch", models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name="CircoptClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll", models.IntegerField()),
                ("name", models.CharField(max_length=122)),
                ("joining_year", models.IntegerField()),
                ("designation", models.CharField(max_length=122)),
                ("branch", models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name="ClubIdentifier",
            fields=[
                (
                    "username",
                    models.CharField(max_length=122, primary_key=True, serialize=False),
                ),
                ("club_name", models.CharField(max_length=122)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FI", "Faculty Incharge"),
                            ("SC", "Student Council"),
                            ("C", "Club"),
                        ],
                        max_length=122,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClubList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=122)),
                ("faculty_coordinator", models.CharField(max_length=122)),
                ("category", models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name="CompetitiveCodingClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll", models.IntegerField()),
                ("name", models.CharField(max_length=122)),
                ("joining_year", models.IntegerField()),
                ("designation", models.CharField(max_length=122)),
                ("branch", models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name="CricketClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll", models.IntegerField()),
                ("name", models.CharField(max_length=122)),
                ("joining_year", models.IntegerField()),
                ("designation", models.CharField(max_length=122)),
                ("branch", models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name="DanceClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll", models.IntegerField()),
                ("name", models.CharField(max_length=122)),
                ("joining_year", models.IntegerField()),
                ("designation", models.CharField(max_length=122)),
                ("branch", models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name="EBSBClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll", models.IntegerField()),
                ("name", models.CharField(max_length=122)),
                ("joining_year", models.IntegerField()),
                ("designation", models.CharField(max_length=122)),
                ("branch", models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=122)),
                ("club_name", models.CharField(max_length=122)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("venue", models.CharField(max_length=122)),
                ("status", models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name="FineartsClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll", models.IntegerField()),
                ("name", models.CharField(max_length=122)),
                ("joining_year", models.IntegerField()),
                ("designation", models.CharField(max_length=122)),
                ("branch", models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name="FootBallClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll", models.IntegerField()),
                ("name", models.CharField(max_length=122)),
                ("joining_year", models.IntegerField()),
                ("designation", models.CharField(max_length=122)),
                ("branch", models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name="IOTClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll", models.IntegerField()),
                ("name", models.CharField(max_length=122)),
                ("joining_year", models.IntegerField()),
                ("designation", models.CharField(max_length=122)),
                ("branch", models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name="KabbadiClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll", models.IntegerField()),
                ("name", models.CharField(max_length=122)),
                ("joining_year", models.IntegerField()),
                ("designation", models.CharField(max_length=122)),
                ("branch", models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name="LiteraryandDebatingClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll", models.IntegerField()),
                ("name", models.CharField(max_length=122)),
                ("joining_year", models.IntegerField()),
                ("designation", models.CharField(max_length=122)),
                ("branch", models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name="MediaClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll", models.IntegerField()),
                ("name", models.CharField(max_length=122)),
                ("joining_year", models.IntegerField()),
                ("designation", models.CharField(max_length=122)),
                ("branch", models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name="MusicClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll", models.IntegerField()),
                ("name", models.CharField(max_length=122)),
                ("joining_year", models.IntegerField()),
                ("designation", models.CharField(max_length=122)),
                ("branch", models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name="NetsecClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll", models.IntegerField()),
                ("name", models.CharField(max_length=122)),
                ("joining_year", models.IntegerField()),
                ("designation", models.CharField(max_length=122)),
                ("branch", models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name="PhotographyClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll", models.IntegerField()),
                ("name", models.CharField(max_length=122)),
                ("joining_year", models.IntegerField()),
                ("designation", models.CharField(max_length=122)),
                ("branch", models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name="RequestOnDuty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll", models.IntegerField()),
                ("club_name", models.CharField(max_length=122)),
                ("date", models.DateField()),
                ("course_code", models.CharField(max_length=122)),
                ("faculty", models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name="RoboticsClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll", models.IntegerField()),
                ("name", models.CharField(max_length=122)),
                ("joining_year", models.IntegerField()),
                ("designation", models.CharField(max_length=122)),
                ("branch", models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name="ScienceClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll", models.IntegerField()),
                ("name", models.CharField(max_length=122)),
                ("joining_year", models.IntegerField()),
                ("designation", models.CharField(max_length=122)),
                ("branch", models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name="TableTennisClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll", models.IntegerField()),
                ("name", models.CharField(max_length=122)),
                ("joining_year", models.IntegerField()),
                ("designation", models.CharField(max_length=122)),
                ("branch", models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name="ThrowBallClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll", models.IntegerField()),
                ("name", models.CharField(max_length=122)),
                ("joining_year", models.IntegerField()),
                ("designation", models.CharField(max_length=122)),
                ("branch", models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name="VolleyBallClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll", models.IntegerField()),
                ("name", models.CharField(max_length=122)),
                ("joining_year", models.IntegerField()),
                ("designation", models.CharField(max_length=122)),
                ("branch", models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name="WebDevClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll", models.IntegerField()),
                ("name", models.CharField(max_length=122)),
                ("joining_year", models.IntegerField()),
                ("designation", models.CharField(max_length=122)),
                ("branch", models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name="YogaClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll", models.IntegerField()),
                ("name", models.CharField(max_length=122)),
                ("joining_year", models.IntegerField()),
                ("designation", models.CharField(max_length=122)),
                ("branch", models.CharField(max_length=122)),
            ],
        ),
    ]
