# Generated by Django 4.2.6 on 2023-10-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_events_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='duration',
        ),
        migrations.AddField(
            model_name='events',
            name='end_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
