# Generated by Django 4.2.5 on 2023-10-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_athleticsfieldclub_athleticstrackclub_badmintonclub_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnDutyRequestClubCultural",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_roll_no", models.CharField(max_length=6)),
                ("date_of_od", models.DateField()),
                ("course_code", models.CharField(max_length=7)),
                ("faculty_name", models.CharField(max_length=122)),
                ("reason", models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name="OnDutyRequestClubSports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_roll_no", models.CharField(max_length=6)),
                ("date_of_od", models.DateField()),
                ("course_code", models.CharField(max_length=7)),
                ("faculty_name", models.CharField(max_length=122)),
                ("reason", models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name="OnDutyRequestClubTechnical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_roll_no", models.CharField(max_length=6)),
                ("date_of_od", models.DateField()),
                ("course_code", models.CharField(max_length=7)),
                ("faculty_name", models.CharField(max_length=122)),
                ("reason", models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name="OnDutyRequestSCCultural",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_roll_no", models.CharField(max_length=6)),
                ("date_of_od", models.DateField()),
                ("course_code", models.CharField(max_length=7)),
                ("faculty_name", models.TextField(max_length=1000)),
                ("reason", models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name="OnDutyRequestSCSports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_roll_no", models.CharField(max_length=6)),
                ("date_of_od", models.DateField()),
                ("course_code", models.CharField(max_length=7)),
                ("faculty_name", models.TextField(max_length=1000)),
                ("reason", models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name="OnDutyRequestSCTechnical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_roll_no", models.CharField(max_length=6)),
                ("date_of_od", models.DateField()),
                ("course_code", models.CharField(max_length=7)),
                ("faculty_name", models.TextField(max_length=1000)),
                ("reason", models.CharField(max_length=122)),
            ],
        ),
        migrations.AddField(
            model_name="clubidentifier",
            name="club_type",
            field=models.CharField(
                choices=[
                    ("cultural", "cultural"),
                    ("technical", "technical"),
                    ("sports", "sports"),
                ],
                default="sports",
                max_length=122,
            ),
        ),
    ]
