# Generated by Django 4.2.6 on 2023-10-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_events_duration_events_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='end_time',
        ),
        migrations.AddField(
            model_name='events',
            name='duration',
            field=models.TimeField(default='01:00:00'),
        ),
    ]
