# Generated by Django 4.2.5 on 2023-10-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_ondutyrequestclubcultural_ondutyrequestclubsports_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnDutyRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_roll_no", models.CharField(max_length=6)),
                ("date_of_od", models.DateField()),
                ("course_code", models.CharField(max_length=7)),
                ("faculty_name", models.CharField(max_length=122)),
                ("reason", models.TextField(max_length=200)),
                (
                    "type_of_club",
                    models.CharField(
                        choices=[
                            ("cultural", "cultural"),
                            ("technical", "technical"),
                            ("sports", "sports"),
                        ],
                        default="cultural",
                        max_length=122,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PSC", "Pending at SC level"),
                            ("PFI", "Pending at FI level"),
                            ("AP", "Approved by faculty incharge"),
                        ],
                        default="PSC",
                        max_length=3,
                    ),
                ),
                ("username", models.CharField(default="user@user", max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name="OnDutyRequestFacultyIncharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_roll_no", models.CharField(max_length=6)),
                ("date_of_od", models.DateField()),
                ("course_code", models.CharField(max_length=7)),
                ("faculty_name", models.TextField(max_length=1000)),
                ("reason", models.CharField(max_length=122)),
                (
                    "type_of_club",
                    models.CharField(
                        choices=[
                            ("cultural", "cultural"),
                            ("technical", "technical"),
                            ("sports", "sports"),
                        ],
                        max_length=122,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OnDutyRequestSC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_roll_no", models.CharField(max_length=6)),
                ("date_of_od", models.DateField()),
                ("course_code", models.CharField(max_length=7)),
                ("faculty_name", models.TextField(max_length=1000)),
                ("reason", models.CharField(max_length=122)),
                (
                    "type_of_club",
                    models.CharField(
                        choices=[
                            ("cultural", "cultural"),
                            ("technical", "technical"),
                            ("sports", "sports"),
                        ],
                        max_length=122,
                    ),
                ),
            ],
        ),
    ]
