# Generated by Django 4.2.6 on 2023-10-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_events_end_time_events_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='endtime',
            field=models.TimeField(default='01:00:00'),
        ),
    ]
