# Generated by Django 4.2.6 on 2023-10-30 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_events_endtime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompetitiveCodingClub',
            new_name='athleticsfield',
        ),
        migrations.RenameModel(
            old_name='FineartsClub',
            new_name='badminton',
        ),
        migrations.RenameModel(
            old_name='MediaClub',
            new_name='basketball',
        ),
        migrations.RenameModel(
            old_name='ChessClub',
            new_name='chess',
        ),
        migrations.RenameModel(
            old_name='DanceClub',
            new_name='circopt',
        ),
        migrations.RenameModel(
            old_name='KabbadiClub',
            new_name='competitivecoding',
        ),
        migrations.RenameModel(
            old_name='CircoptClub',
            new_name='cricket',
        ),
        migrations.RenameModel(
            old_name='EBSBClub',
            new_name='dance',
        ),
        migrations.RenameModel(
            old_name='RoboticsClub',
            new_name='ebsb',
        ),
        migrations.RenameModel(
            old_name='YogaClub',
            new_name='finearts',
        ),
        migrations.RenameModel(
            old_name='TableTennisClub',
            new_name='football',
        ),
        migrations.RenameModel(
            old_name='WebDevClub',
            new_name='iot',
        ),
        migrations.RenameModel(
            old_name='PhotographyClub',
            new_name='kabbadi',
        ),
        migrations.RenameModel(
            old_name='ScienceClub',
            new_name='literaryanddebating',
        ),
        migrations.RenameModel(
            old_name='CricketClub',
            new_name='media',
        ),
        migrations.RenameModel(
            old_name='ThrowBallClub',
            new_name='music',
        ),
        migrations.RenameModel(
            old_name='FootBallClub',
            new_name='netsec',
        ),
        migrations.RenameModel(
            old_name='MusicClub',
            new_name='photography',
        ),
        migrations.RenameModel(
            old_name='BadmintonClub',
            new_name='robotics',
        ),
        migrations.RenameModel(
            old_name='IOTClub',
            new_name='science',
        ),
        migrations.RenameModel(
            old_name='NetsecClub',
            new_name='tabletennis',
        ),
        migrations.RenameModel(
            old_name='AthleticsFieldClub',
            new_name='throwball',
        ),
        migrations.RenameModel(
            old_name='VolleyBallClub',
            new_name='volleyBall',
        ),
        migrations.RenameModel(
            old_name='BasketBallClub',
            new_name='webDev',
        ),
        migrations.RenameModel(
            old_name='LiteraryandDebatingClub',
            new_name='yoga',
        ),
    ]
