# Generated by Django 4.2.6 on 2023-10-30 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_competitivecodingclub_athleticsfield_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clublist',
            old_name='name',
            new_name='club_name',
        ),
    ]
