# Generated by Django 4.2.6 on 2023-11-02 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_badmintonclub_athleticsfield_and_more'),
        ('home', '0007_rename_name_clublist_club_name'),
    ]

    operations = [
    ]
